GET http://localhost:3000/api/movies

###

GET http://localhost:3000/api/movies/0

###

POST http://localhost:3000/api/movies
Content-Type: application/json

{
    "title": "Citizen Kane",
    "released": 1941,
    "duration": 119   
}

###

PUT http://localhost:3000/api/movies/0
Content-Type: application/json

{
    "title": "The Matrix",
    "released": 1999,
    "duration": 136
}

###

DELETE http://localhost:3000/api/movies/0