GET http://localhost:3000/api/movies

###

GET http://localhost:3000/api/movies/1d06a69b-3849-444b-b0bb-d18e2814fd22

###

POST http://localhost:3000/api/movies
Content-Type: application/json

{
    "title": "Citizen Kane",
    "released": 1941,
    "duration": 119,
    "What if we send extra information" : true,
    "Weird harmfull code": "Some code"  
}

###

PUT http://localhost:3000/api/movies/1d06a69b-3849-444b-b0bb-d18e2814fd22
Content-Type: application/json

{
    "title": "The Matrix",
    "released": "1999",
    "duration": 136
}

###

DELETE http://localhost:3000/api/movies/1d06a69b-3849-444b-b0bb-d18e2814fd22